export const toolIconMap: Record<string, string> = {
  Figma: "/images/tools/figma.png",
  Figjam: "/images/tools/figjam.png",
  Notion: "/images/tools/notion.png",
  "Google Workspace": "/images/tools/google-workspace.png",
  Slack: "/images/tools/slack.png",
  Bubble: "/images/tools/bubble.png",
  "Next.js": "/images/tools/nextjs.png",
  shadcn: "/images/tools/shadcn.png",
  GPT: "/images/tools/gpt.png",
  Github: "/images/tools/github.png",
  Gemini: "/images/tools/gemini.png",
  Vercel: "/images/tools/vercel.png",
  Supabase: "/images/tools/supabase.png",
  Cursor: "/images/tools/cursor.png",
  Claude: "/images/tools/claude.png",
  Midjourney: "/images/tools/midjourney.png",
  Gitlab: "",
  "VS Code": "",
  Clerk: "",
};
